name: shoe_store_manager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  file_selector: ^1.0.3
  flutter_slidable: ^3.1.2
  shared_preferences: ^2.2.3
  window_manager: ^0.3.9
  sqflite_common_ffi: ^2.3.7+1
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  cryptography: ^2.7.0
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/binary_devs.png
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf

# ==================================================
# ✅ APP ICON CONFIG (JASHTË flutter:)
# ==================================================
flutter_launcher_icons:
  image_path: "assets/icons/binary_devs.png"
  windows:
    generate: true
    icon_path: "assets/icons/binary_devs.png"
  macos:
    generate: true
    icon_path: "assets/icons/binary_devs.png"
  linux:
    generate: true
    icon_path: "assets/icons/binary_devs.png"